// src/components/CorrectGuesses.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { useMainStore } from "../store";
import { gridify } from "../utils";

import { useI18n } from "vue-i18n";
import en from "../locales/en.json";

const { t } = useI18n({
  inheritLocale: true,
  messages: {
    en,
  },
});

const store = useMainStore();
// showWords el-collapse has 2 elems when expanded, 1 when collapsed.
const showWords = ref([false]);
const numCorrectMessage = computed(() => {
  return t("foundWords", store.getCorrectGuesses.length);
});

const lastFiveGuesses = computed(() => {
  const numGuessesToShow = Math.min(store.getCorrectGuesses.length, 5);
  return store.getCorrectGuesses.reverse().slice(0, numGuessesToShow);
});

// alphabetical when expanded, in order found when collapsed.
const gridData = computed(
  () => gridify({ arr: Array.from(store.getCorrectGuesses).sort(), size: 3 })
  // gridify({ arr: Array.from(Array(100).keys()), size: 3 })
);
</script>

<template>
  <el-collapse
    v-model="showWords"
    @change="showWords.length == 2 ? $emit('open') : $emit('close')">
    <el-collapse-item>
      <template #title>
        <template v-if="showWords.length === 2">
          {{ numCorrectMessage }}
        </template>
        <template v-else-if="lastFiveGuesses.length === 0">
          {{ t("Your words") }}...
        </template>
        <template v-else>
          <span
            v-for="(guess, index) in lastFiveGuesses"
            :key="guess"
            :class="store.cellClassName({ row: [guess], columnIndex: -1 })">
            {{ guess }}{{ index === lastFiveGuesses.length - 1 ? "" : ", " }}
          </span>
          <span v-if="lastFiveGuesses.length === 5"> ... </span>
        </template>
      </template>
      <el-table
        :data="gridData"
        class="correct-guesses-table"
        :cell-class-name="store.cellClassName">
        <el-table-column property="1" label="" />
        <el-table-column property="2" label="" />
        <el-table-column property="3" label="" />
      </el-table>
    </el-collapse-item>
  </el-collapse>
</template>

<style scoped lang="scss">
@import "../assets/styles/_variables";

.correct-guesses-table {
  min-height: 50vh;
}

html.dark .el-collapse {
  background-color: $bl-el-plus-dark-bg;
}
</style>

// src/components/CorrectGuesses.tsx
import React, { useState, useEffect, useMemo } from "react";
import { useMainStore } from "../store";
import { gridify } from "../utils";
import { useTranslation } from "../hooks/useTranslation";
import "./CorrectGuesses.scss";

interface CorrectGuessesProps {
  onOpen: () => void;
  onClose: () => void;
}

export const CorrectGuesses: React.FC<CorrectGuessesProps> = ({
  onOpen,
  onClose,
}) => {
  const store = useMainStore();
  const { t } = useTranslation();
  const [showWords, setShowWords] = useState(false);

  const correctGuesses = store.getCorrectGuesses();

  const numCorrectMessage = useMemo(() => {
    return t("foundWords", correctGuesses.length);
  }, [correctGuesses.length, t]);

  const lastFiveGuesses = useMemo(() => {
    const numGuessesToShow = Math.min(correctGuesses.length, 5);
    return [...correctGuesses].reverse().slice(0, numGuessesToShow);
  }, [correctGuesses]);

  const gridData = useMemo(
    () => gridify({ arr: Array.from(correctGuesses).sort(), size: 3 }),
    [correctGuesses]
  );

  useEffect(() => {
    if (showWords) {
      onOpen();
    } else {
      onClose();
    }
  }, [showWords, onOpen, onClose]);

  const getCellClassName = (word: string | undefined) => {
    if (!word) return "";
    return store.cellClassName({ row: [word], columnIndex: -1 });
  };

  return (
    <div className="correct-guesses-collapse">
      <div
        className={`collapse-header ${showWords ? "expanded" : ""}`}
        onClick={() => setShowWords(!showWords)}>
        <div className="collapse-title">
          {showWords ? (
            numCorrectMessage
          ) : lastFiveGuesses.length === 0 ? (
            <span>{t("Your words")}...</span>
          ) : (
            <>
              {lastFiveGuesses.map((guess, index) => (
                <span key={guess} className={getCellClassName(guess)}>
                  {guess}
                  {index === lastFiveGuesses.length - 1 ? "" : ", "}
                </span>
              ))}
              {lastFiveGuesses.length === 5 && <span> ... </span>}
            </>
          )}
        </div>
        <span className="collapse-arrow">{showWords ? "▲" : "▼"}</span>
      </div>
      {showWords && (
        <div className="collapse-content">
          <table className="correct-guesses-table">
            <tbody>
              {gridData.map((row: any, rowIndex: number) => (
                <tr key={rowIndex}>
                  <td className={getCellClassName(row["1"])}>{row["1"]}</td>
                  <td className={getCellClassName(row["2"])}>{row["2"]}</td>
                  <td className={getCellClassName(row["3"])}>{row["3"]}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};
