// src/components/Progress.tsx
import React, { useState } from "react";
import { useMainStore } from "../store";
import { useTranslation } from "../hooks/useTranslation";
import { Modal } from "./Modal";
import "./Progress.scss";

export const Progress: React.FC = () => {
  const store = useMainStore();
  const { t } = useTranslation();
  const [showRanking, setShowRanking] = useState(false);

  const progressIndex = store.getProgressIndex();
  const progressPercentage = store.getProgressPercentage();
  const userScore = store.getUserScore();
  const scoreLevels = store.getScoreLevels();

  return (
    <>
      <Modal
        visible={showRanking}
        title={t("Ranking")}
        onClose={() => setShowRanking(false)}>
        <div className="ranking-dialog">
          <p>{t("RankMSG")}:</p>
          <ul>
            {scoreLevels.map((scoreLevel: number, index: number) => (
              <li key={`ranking${index}`}>
                {t(`rank.${index}`)} ({scoreLevel})
              </li>
            ))}
          </ul>
        </div>
      </Modal>
      <div className="row" onClick={() => setShowRanking(true)}>
        <strong className="rank-level">{t(`rank.${progressIndex}`)}</strong>
        <div className="progress-bar">
          <div className="progress-bar-outer">
            <div
              className="progress-bar-inner"
              style={{ width: `${progressPercentage}%` }}
            />
          </div>
          <span className="progress-text">{userScore}</span>
        </div>
      </div>
    </>
  );
};

// src/components/Progress.vue
<script setup lang="ts">
import { ref } from "vue";
import { useMainStore } from "../store";

const store = useMainStore();
const showRanking = ref(false);
</script>

<template>
  <el-dialog v-model="showRanking" :title="$t('Ranking')">
    <div class="ranking-dialog">
      <p>{{ $t("RankMSG") }}:</p>
      <ul>
        <li
          v-for="(scoreLevel, index) in store.getScoreLevels"
          :key="`ranking${index}`">
          {{ $t(`rank.${index}`) }} ({{ scoreLevel }})
        </li>
      </ul>
    </div>
  </el-dialog>
  <div class="row" @click="showRanking = true">
    <strong class="rank-level">
      {{ $t(`rank.${store.getProgressIndex}`) }}
    </strong>
    <el-progress
      :percentage="store.getProgressPercentage"
      :stroke-width="20"
      color="#20a866"
      :format="() => store.getUserScore" />
  </div>
</template>

<style scoped lang="scss">
@import "../assets/styles/_variables";

.row {
  margin: 20px;
}

.ranking-dialog {
  text-align: left;
}

html.dark .row strong {
  color: $bl-grey;
}

@media only screen and (max-width: 700px) {
  .row {
    margin: 10px;
  }
}
</style>
